//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTDB.Common {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RTDB.Common.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 组名称已存在，不能重复加载 的本地化字符串。
        /// </summary>
        internal static string CVariableGroup_AddGroup_GroupeNameIsExist {
            get {
                return ResourceManager.GetString("CVariableGroup_AddGroup_GroupeNameIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加组的名称不为空 的本地化字符串。
        /// </summary>
        internal static string CVariableGroup_AddGroup_GroupNameIsNull {
            get {
                return ResourceManager.GetString("CVariableGroup_AddGroup_GroupNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未检索到组节点 的本地化字符串。
        /// </summary>
        internal static string UnitofWork_AddGroup_currentVariableGroup {
            get {
                return ResourceManager.GetString("UnitofWork_AddGroup_currentVariableGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 analogElement is null 的本地化字符串。
        /// </summary>
        internal static string VariableBase_AddVar_analogElement_is_null {
            get {
                return ResourceManager.GetString("VariableBase_AddVar_analogElement_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 digitalElement is null 的本地化字符串。
        /// </summary>
        internal static string VariableBase_AddVar_digitalElement_is_null {
            get {
                return ResourceManager.GetString("VariableBase_AddVar_digitalElement_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 stringElement is null 的本地化字符串。
        /// </summary>
        internal static string VariableBase_AddVar_stringElement_is_null {
            get {
                return ResourceManager.GetString("VariableBase_AddVar_stringElement_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 varObj is null 的本地化字符串。
        /// </summary>
        internal static string VariableBase_EditVar_varObj_is_null {
            get {
                return ResourceManager.GetString("VariableBase_EditVar_varObj_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加到组的变量为空 的本地化字符串。
        /// </summary>
        internal static string VariableGroup_AddVariable_variable_is_null {
            get {
                return ResourceManager.GetString("VariableGroup_AddVariable_variable_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前组已存在相同变量名的变量 的本地化字符串。
        /// </summary>
        internal static string VariableGroup_addVariable_variableName_is_Exist {
            get {
                return ResourceManager.GetString("VariableGroup_addVariable_variableName_is_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父祖为空 的本地化字符串。
        /// </summary>
        internal static string VariableGroup_IsExistGroupName_parentGroup_is_null {
            get {
                return ResourceManager.GetString("VariableGroup_IsExistGroupName_parentGroup_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要修改的变量组新名称为空 的本地化字符串。
        /// </summary>
        internal static string VariableGroup_ReGroupName_groupName_Is_Null {
            get {
                return ResourceManager.GetString("VariableGroup_ReGroupName_groupName_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除组为根组，不能删除 的本地化字符串。
        /// </summary>
        internal static string VariableGroup_RemoveGroup_DeleteGroup_Is_RootGroup {
            get {
                return ResourceManager.GetString("VariableGroup_RemoveGroup_DeleteGroup_Is_RootGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要修改组名称的组为空 的本地化字符串。
        /// </summary>
        internal static string VariableGroup_ReplaceGroupName_editGroup_is_null {
            get {
                return ResourceManager.GetString("VariableGroup_ReplaceGroupName_editGroup_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该变量已经存在 的本地化字符串。
        /// </summary>
        internal static string VariableRepository_AddVar_VariableIsExist {
            get {
                return ResourceManager.GetString("VariableRepository_AddVar_VariableIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加变量为空 的本地化字符串。
        /// </summary>
        internal static string VariableRepository_AddVar_VariableIsNull {
            get {
                return ResourceManager.GetString("VariableRepository_AddVar_VariableIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父节点字符串为空或不存在 的本地化字符串。
        /// </summary>
        internal static string VariableUnitOfWork_AddGroup_parentVariableGroupIdIsNullOrEmpty {
            get {
                return ResourceManager.GetString("VariableUnitOfWork_AddGroup_parentVariableGroupIdIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前组节点为空 的本地化字符串。
        /// </summary>
        internal static string VariableUnitOfWork_AddGroupMethod_currentNodeIsNull {
            get {
                return ResourceManager.GetString("VariableUnitOfWork_AddGroupMethod_currentNodeIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 变量名称重复，不能修改 的本地化字符串。
        /// </summary>
        internal static string VariableUnitOfWork_EditVariable_AvarialeNameExist {
            get {
                return ResourceManager.GetString("VariableUnitOfWork_EditVariable_AvarialeNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名字为空或不存在 的本地化字符串。
        /// </summary>
        internal static string VariableUnitOfWork_IsExistName_nameIsNullOrEmpty {
            get {
                return ResourceManager.GetString("VariableUnitOfWork_IsExistName_nameIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除组为根组节点或不存在
        /// 的本地化字符串。
        /// </summary>
        internal static string VariableUnitOfWork_RemoveGroup_curVariableGroupIdIsNullOrEmpty {
            get {
                return ResourceManager.GetString("VariableUnitOfWork_RemoveGroup_curVariableGroupIdIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 变量上下文为空 的本地化字符串。
        /// </summary>
        internal static string VariableUnitOfWork_VariableUnitOfWork_variableContextIsNull {
            get {
                return ResourceManager.GetString("VariableUnitOfWork_VariableUnitOfWork_variableContextIsNull", resourceCulture);
            }
        }
    }
}
