//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionTestProject.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FunctionTestProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid selection 的本地化字符串。
        /// </summary>
        internal static string FunctionTestForm_BiginEdit_Invalid_selection {
            get {
                return ResourceManager.GetString("FunctionTestForm_BiginEdit_Invalid_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 node 的本地化字符串。
        /// </summary>
        internal static string FunctionTestForm_GetInitVarName_node {
            get {
                return ResourceManager.GetString("FunctionTestForm_GetInitVarName_node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 源路径字符串为空 的本地化字符串。
        /// </summary>
        internal static string FunctionTestForm_GetVariableGroupPath_sourceIsNull {
            get {
                return ResourceManager.GetString("FunctionTestForm_GetVariableGroupPath_sourceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No tree node selected or selected node is a root node.
        ///Editing of root nodes is not allowed. 的本地化字符串。
        /// </summary>
        internal static string FunctionTestForm_ToolStripMenuItemRenameGroupClick_ {
            get {
                return ResourceManager.GetString("FunctionTestForm_ToolStripMenuItemRenameGroupClick_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid tree node label.
        ///The invalid characters are: &apos;@&apos;,&apos;.&apos;, &apos;,&apos;, &apos;!&apos; 的本地化字符串。
        /// </summary>
        internal static string FunctionTestForm_TreeViewFunctionTest_AfterLabelEdit_ {
            get {
                return ResourceManager.GetString("FunctionTestForm_TreeViewFunctionTest_AfterLabelEdit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid tree node label.
        ///The label cannot be blank 的本地化字符串。
        /// </summary>
        internal static string FunctionTestForm_TreeViewFunctionTest_AfterLabelEdit_ContentIsBlank {
            get {
                return ResourceManager.GetString("FunctionTestForm_TreeViewFunctionTest_AfterLabelEdit_ContentIsBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Node Label Edit 的本地化字符串。
        /// </summary>
        internal static string FunctionTestForm_TreeViewFunctionTestAfterLabelEdit_Node_Label_Edit {
            get {
                return ResourceManager.GetString("FunctionTestForm_TreeViewFunctionTestAfterLabelEdit_Node_Label_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 变量组名不能重复 的本地化字符串。
        /// </summary>
        internal static string FunctionTestForm_TreeViewFunctionTestAfterLabelEdit_NodeNameIsExist {
            get {
                return ResourceManager.GetString("FunctionTestForm_TreeViewFunctionTestAfterLabelEdit_NodeNameIsExist", resourceCulture);
            }
        }
    }
}
