//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VariableObj {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VariableObj.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 组名称已存在，不能重复加载 的本地化字符串。
        /// </summary>
        internal static string CVariableGroup_AddGroup_GroupeNameIsExist {
            get {
                return ResourceManager.GetString("CVariableGroup_AddGroup_GroupeNameIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加组的名称不为空 的本地化字符串。
        /// </summary>
        internal static string CVariableGroup_AddGroup_GroupNameIsNull {
            get {
                return ResourceManager.GetString("CVariableGroup_AddGroup_GroupNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父节点为空 的本地化字符串。
        /// </summary>
        internal static string VariableGroup_AddGroup_parentNodeIsNull {
            get {
                return ResourceManager.GetString("VariableGroup_AddGroup_parentNodeIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 parentGroup is null 的本地化字符串。
        /// </summary>
        internal static string VariableGroup_IsExistGroupName_parentGroup_is_null {
            get {
                return ResourceManager.GetString("VariableGroup_IsExistGroupName_parentGroup_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 editGroup is null 的本地化字符串。
        /// </summary>
        internal static string VariableGroup_ReplaceGroupName_editGroup_is_null {
            get {
                return ResourceManager.GetString("VariableGroup_ReplaceGroupName_editGroup_is_null", resourceCulture);
            }
        }
    }
}
